version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: typescript_api
      POSTGRES_USER: typescript_user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  config:
    build:
      context: devU-api/scripts
    command: "./generateConfig.sh config/newconfig.yml"
    image: ubautograding/devtools
    volumes:
      - ./devU-api/config:/config
  web:
    build: devU-api
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      - "db"
    ports:
      - '3001:3001'

