version: '3.8'
services:
  db:
    # Runs the PostgreSQL database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: typescript_api
      POSTGRES_USER: typescript_user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  config:
    # Generates a config file for the API
    build:
      context: devU-api/scripts
    command: "./generateConfig.sh config/default.yml"
    image: ubautograding/devtools
    volumes:
      - ./devU-api/config:/config
  web:
    # Runs the API
    build: devU-api
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      db:
        condition: service_started
      config:
        condition: service_completed_successfully
    ports:
      - '3001:3001'
  client:
    # Builds the front end and exports static files to ./dist
    build:
      dockerfile: ../Dockerfile-client
      context: devU-client
    volumes:
      - ./dist:/out
  nginx:
    # Hosts the front end static files from ./dist/local thorough a web server
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./dist/local:/usr/share/nginx/html
    ports:
      - "9000:80"
